### PR TITLE
AutoML Enviornment

### LINKED ISSUE #33: Try out AutoML for classification
After developing a model and performing a parameter study on your own, it's time for using some frameworks to support your machine learning journey.

Take a look at Auto-PyTorch

And try a basic AutoML Search for finding a better network architecture and well selected hyperparameters.

There is an example for tabular data with classification in the projects repository.

https://github.com/automl/Auto-PyTorch/blob/56a2ac1d69c7c61a847c678879a67f5d3672b3e8/examples/20_basics/example_tabular_classification.py

Focus on getting the AutoML process running. I will add an issue for documentation.

### PR DESCRIPTION
**Pull request by RicoKursidem**
This pull request introduces a Docker Image in the Docker Environment Folder. In it, all the Dependencies for a AutoPyTorch Program are installed, and this repository is also downloaded. Until now, the AutoML Branch is cloned, but this can be changed via the Arguments in the docker compose file in the future ``main``.

For the Arguments in the compose file, I used:
``` LookML
args:
        - gh_token= <userGithubToken>
        - gh_email= <userEmail>
        - gh_uname=RicoKursidem
        - gh_repo_owner=RicoKursidem
        - gh_repo_name=dhbw-deep-groove-with-pytorch
        - gh_branch=AutoML
```
In the Dockercontainer the following command will start the python AutoML script

``` Shell
python3 /dhbw-deep-groove-with-pytorch/deep_groove_project/src/main.py 
```

TODO:

1)
I still have some warnings I could not figure out. Some results can't be shown. Error Message:
``` Shell
[WARNING] [2023-05-14 15:11:08,439:Client-AutoPyTorch:RefitLogger:42] Something went wrong while processing the results of catboost.with additional_info: {'opt_loss': {'accuracy': 0.035190615835777095}, 'duration': 32.152493476867676, 'num_run': 25, 'train_loss': {'accuracy': 0.0}, 'test_loss': {'accuracy': 0.035190615835777095}, 'configuration': 'catboost', 'budget': 50.0, 'configuration_origin': 'traditional'} and status_type: StatusType.SUCCESS. Refer to the log file for more information.
Skipping for now.
```
2)
I get an error with Timeout, but did not find the parameter to extend the maximal Runtime. 

```
[WARNING] [2023-05-14 15:39:34,482:Client-AutoPyTorch:RefitLogger:42] Not enough time to fit all machine learning models.Please consider increasing the run time to further improve performance.
```

I will work on these warnings this week. 

Solutions: 20.05.2023

1)
- I cannot find out why these warnings pop up. There is a reference to the logs, but I don't find them. Because of time, I will first finish the Documentation of this part and then continue looking for an explanation. 

2) 
- Adding batch_type='runtime' so the max_batch Parameter is used as seconds
- Setting max_batch = 500, so all models have time to train.

### CODE REVIEW

**Comment by philippabele** [comment]
@RicoKursidem At the beginning of this PR you mentioned some ToDos. 

Did you finished them?

**Comment by philippabele** [comment]
@RicoKursidem This PR contains three Dockerfiles. Could you help me and explain me the reason for this?

**Comment by RicoKursidem** [comment]
Hi @philippabele 

I did not finish the Todos yet. I will do it this weekend. 

There are tree Dockerfiles because I had three different attempts to build the container. The "Dockerfile" is the correct one. I will delete the other two.

**Comment by RicoKursidem** [comment]
Solutions: 20.05.2023
1)
I cannot find out why these warnings pop up. There is a reference to the logs, but I don't find them. Because of time, I will first finish the Documentation of this part and then continue looking for an explanation.
2)
Adding batch_type='runtime' so the max_batch Parameter is used as seconds
Setting max_batch = 500, so all models have time to train.

**Comment by philippabele** [comment]
@RicoKursidem 

Please let me know, when I can test the Dockerfile.

Please let me know, when there is a documentation it could take a look at. Please create a new PR for the documentation.

**Comment by RicoKursidem** [comment]
You can test the Dockerfile. I will publish the Documentation PR today.

**Pull request merged**
