### PR TITLE
First steps with pytorch

### LINKED ISSUE #13: First steps with PyTorch
- Start locally

https://pytorch.org/get-started/locally/

I would prefer a installation on Windows, with cuda and pip.

- Learn the basics

https://pytorch.org/tutorials/beginner/basics/intro.html

Great tutorial with all steps of a complete Machine Learning workflow

- Create a PR and add the source to our repo in an own sub folder

### PR DESCRIPTION
**Pull request by RicoKursidem**
I added the project folder and added a tutorial folder for the pandas and PyTorch folders. 
I will continue with the tutorial in the following days

this pull request will resolve #13

### CODE REVIEW

**Review by philippabele — CHANGES_REQUESTED** [review]
It is very difficult for me to review this PR. There are several reasons why:

- please do not check in general available data like the FashionMNIST dataset
- write your main code in python classes and seperate them from your notebooks

**Comment by philippabele** [comment]
@RicoKursidem Jupyter Notebooks are great to play around with data, but they are terrible to handle in a repo.

I will approve this PR, because it is only a tutorial. But for the main application we have to move away from notebooks to pure python. In order to see your actual work faster during code reviews, this will improve the speed and quality of my support for your project.

The reuse of your source code in future projects will also be easier, if the code is split into pure application code and pure python classes. Jupyter Notebooks will only be used for demo purpose.

Is this okay for you?

**Review by philippabele — APPROVED** [review]

**Comment by RicoKursidem** [comment]
Hi @philippabele 

I just used the notebooks as a place to do the tutorial and save code snippets for later use.
I'm fine with the approval of this pull request, but I didn't finish the tutorial yet. I plan to complete it tomorrow.

I can also add the PyTorch tutorial notebooks to the .gitignore and use them only on my system. 

I'm aware that I should work with classes and an IDE that supports this kind of coding better than VS Code.
Is it ok if I use PyCharm to develop this Project, or is there a better IDE?

**Comment by philippabele** [comment]
I work with VS Code and value it.

There are plenty of extensions to fit it to your personal use case.

**Comment by RicoKursidem** [comment]
Ok. Thank you. I will work with VS Code. :)

**Comment by RicoKursidem** [comment]
I did all tutorials and added a Jupyter file to document them.

I also made this pull request ready for review, and it can be merged to the main branch now

**Pull request merged**
